In [6]:
import FinanceDataReader as fdr

df_krx = fdr.StockListing('KRX')
df_krx.head()

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,72400,2,-900,-1.23,72900,73100,72300,9740504,707795779500,432212256620000,5969782550,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,166600,2,-5300,-3.08,165000,168900,164700,3450905,575360328400,121285194009000,728002365,STK
2,373220,KR7373220003,LG에너지솔루션,KOSPI,,400500,2,-2000,-0.50,402500,407000,399000,104044,41874912500,93717000000000,234000000,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,830000,2,-8000,-0.95,842000,843000,825000,63779,53150264000,59074420000000,71174000,STK
4,005380,KR7005380001,현대차,KOSPI,,243500,2,-9500,-3.75,251000,252500,242000,1178615,291020168000,51507921711000,211531506,STK